package com.example.permission.mapper;

import com.example.permission.entity.TEmployeeRole;

public interface TEmployeeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_role
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_role
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int insert(TEmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_role
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int insertSelective(TEmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_role
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    TEmployeeRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_role
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int updateByPrimaryKeySelective(TEmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee_role
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int updateByPrimaryKey(TEmployeeRole record);
}