package com.example.permission.mapper;

import com.example.permission.entity.TSystemDictionaryItem;

public interface TSystemDictionaryItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary_item
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary_item
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int insert(TSystemDictionaryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary_item
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int insertSelective(TSystemDictionaryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary_item
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    TSystemDictionaryItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary_item
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int updateByPrimaryKeySelective(TSystemDictionaryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary_item
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int updateByPrimaryKey(TSystemDictionaryItem record);
}