package com.example.blog.mapper;

import com.example.blog.entity.Resource;
import org.springframework.stereotype.Component;

@Component
public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    Resource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    int updateByPrimaryKey(Resource record);
}