package com.example.blog.mapper;

import com.example.blog.entity.Upvote;
import org.springframework.stereotype.Component;

@Component
public interface UpvoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    int insert(Upvote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    int insertSelective(Upvote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    Upvote selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    int updateByPrimaryKeySelective(Upvote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_upvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    int updateByPrimaryKey(Upvote record);
}