package com.example.permission.entity;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.sn
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.department_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.dir_path
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String dirPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.manager_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.parent_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.id
     *
     * @return the value of t_department.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.id
     *
     * @param id the value for t_department.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.sn
     *
     * @return the value of t_department.sn
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.sn
     *
     * @param sn the value for t_department.sn
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.department_name
     *
     * @return the value of t_department.department_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.department_name
     *
     * @param departmentName the value for t_department.department_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.dir_path
     *
     * @return the value of t_department.dir_path
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getDirPath() {
        return dirPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.dir_path
     *
     * @param dirPath the value for t_department.dir_path
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setDirPath(String dirPath) {
        this.dirPath = dirPath == null ? null : dirPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.state
     *
     * @return the value of t_department.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.state
     *
     * @param state the value for t_department.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.manager_id
     *
     * @return the value of t_department.manager_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.manager_id
     *
     * @param managerId the value for t_department.manager_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.parent_id
     *
     * @return the value of t_department.parent_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.parent_id
     *
     * @param parentId the value for t_department.parent_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }
}