package com.example.permission.entity;

public class TEmployeeRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_role.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_role.employee_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee_role.role_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_role.id
     *
     * @return the value of t_employee_role.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_role.id
     *
     * @param id the value for t_employee_role.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_role.employee_id
     *
     * @return the value of t_employee_role.employee_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_role.employee_id
     *
     * @param employeeId the value for t_employee_role.employee_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee_role.role_id
     *
     * @return the value of t_employee_role.role_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee_role.role_id
     *
     * @param roleId the value for t_employee_role.role_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}