package com.example.permission.mapper;

import com.example.permission.entity.TSystemDictionary;

public interface TSystemDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int insert(TSystemDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int insertSelective(TSystemDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    TSystemDictionary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int updateByPrimaryKeySelective(TSystemDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_dictionary
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    int updateByPrimaryKey(TSystemDictionary record);
}