package com.example.permission.entity;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.age
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.gender
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.tel
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.email
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.qq
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.wechat
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.input_time
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private Date inputTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.seller_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String sellerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.input_user_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String inputUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.job_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.salary_level_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String salaryLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customer_source_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String customerSourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_name
     *
     * @return the value of t_customer.customer_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_name
     *
     * @param customerName the value for t_customer.customer_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.age
     *
     * @return the value of t_customer.age
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.age
     *
     * @param age the value for t_customer.age
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.gender
     *
     * @return the value of t_customer.gender
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.gender
     *
     * @param gender the value for t_customer.gender
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.tel
     *
     * @return the value of t_customer.tel
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.tel
     *
     * @param tel the value for t_customer.tel
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.email
     *
     * @return the value of t_customer.email
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.email
     *
     * @param email the value for t_customer.email
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.qq
     *
     * @return the value of t_customer.qq
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.qq
     *
     * @param qq the value for t_customer.qq
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.wechat
     *
     * @return the value of t_customer.wechat
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.wechat
     *
     * @param wechat the value for t_customer.wechat
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.input_time
     *
     * @return the value of t_customer.input_time
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.input_time
     *
     * @param inputTime the value for t_customer.input_time
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.seller_id
     *
     * @return the value of t_customer.seller_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.seller_id
     *
     * @param sellerId the value for t_customer.seller_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.input_user_id
     *
     * @return the value of t_customer.input_user_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getInputUserId() {
        return inputUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.input_user_id
     *
     * @param inputUserId the value for t_customer.input_user_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setInputUserId(String inputUserId) {
        this.inputUserId = inputUserId == null ? null : inputUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.job_id
     *
     * @return the value of t_customer.job_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.job_id
     *
     * @param jobId the value for t_customer.job_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.salary_level_id
     *
     * @return the value of t_customer.salary_level_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getSalaryLevelId() {
        return salaryLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.salary_level_id
     *
     * @param salaryLevelId the value for t_customer.salary_level_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setSalaryLevelId(String salaryLevelId) {
        this.salaryLevelId = salaryLevelId == null ? null : salaryLevelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.state
     *
     * @return the value of t_customer.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.state
     *
     * @param state the value for t_customer.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customer_source_id
     *
     * @return the value of t_customer.customer_source_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getCustomerSourceId() {
        return customerSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customer_source_id
     *
     * @param customerSourceId the value for t_customer.customer_source_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setCustomerSourceId(String customerSourceId) {
        this.customerSourceId = customerSourceId == null ? null : customerSourceId.trim();
    }
}