package com.example.permission.entity;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.employee_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.password
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.real_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.tel
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.email
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.input_time
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private Date inputTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.department_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.id
     *
     * @return the value of t_employee.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.id
     *
     * @param id the value for t_employee.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.employee_name
     *
     * @return the value of t_employee.employee_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.employee_name
     *
     * @param employeeName the value for t_employee.employee_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.password
     *
     * @return the value of t_employee.password
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.password
     *
     * @param password the value for t_employee.password
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.real_name
     *
     * @return the value of t_employee.real_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.real_name
     *
     * @param realName the value for t_employee.real_name
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.tel
     *
     * @return the value of t_employee.tel
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.tel
     *
     * @param tel the value for t_employee.tel
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.email
     *
     * @return the value of t_employee.email
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.email
     *
     * @param email the value for t_employee.email
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.input_time
     *
     * @return the value of t_employee.input_time
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.input_time
     *
     * @param inputTime the value for t_employee.input_time
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.state
     *
     * @return the value of t_employee.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.state
     *
     * @param state the value for t_employee.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.department_id
     *
     * @return the value of t_employee.department_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.department_id
     *
     * @param departmentId the value for t_employee.department_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }
}