package com.example.permission.entity;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.permission_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.resource
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String resource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.menu_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.sn
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    private String sn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.id
     *
     * @return the value of t_permission.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.id
     *
     * @param id the value for t_permission.id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.permission_id
     *
     * @return the value of t_permission.permission_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.permission_id
     *
     * @param permissionId the value for t_permission.permission_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setPermissionId(String permissionId) {
        this.permissionId = permissionId == null ? null : permissionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.resource
     *
     * @return the value of t_permission.resource
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.resource
     *
     * @param resource the value for t_permission.resource
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.state
     *
     * @return the value of t_permission.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.state
     *
     * @param state the value for t_permission.state
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.menu_id
     *
     * @return the value of t_permission.menu_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.menu_id
     *
     * @param menuId the value for t_permission.menu_id
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.sn
     *
     * @return the value of t_permission.sn
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.sn
     *
     * @param sn the value for t_permission.sn
     *
     * @mbg.generated Wed Aug 01 17:03:43 CST 2018
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }
}