package com.example.blog.entity;

import java.util.Date;

public class LoginLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.user_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.ip
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_login_log.create_time
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.id
     *
     * @return the value of t_login_log.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.id
     *
     * @param id the value for t_login_log.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.user_id
     *
     * @return the value of t_login_log.user_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.user_id
     *
     * @param userId the value for t_login_log.user_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.ip
     *
     * @return the value of t_login_log.ip
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.ip
     *
     * @param ip the value for t_login_log.ip
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_login_log.create_time
     *
     * @return the value of t_login_log.create_time
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_login_log.create_time
     *
     * @param createTime the value for t_login_log.create_time
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}