package com.example.blog.entity;

public class Resource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_name
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.url
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.enabled
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.remark
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.id
     *
     * @return the value of t_resource.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.id
     *
     * @param id the value for t_resource.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_name
     *
     * @return the value of t_resource.resource_name
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_name
     *
     * @param resourceName the value for t_resource.resource_name
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.url
     *
     * @return the value of t_resource.url
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.url
     *
     * @param url the value for t_resource.url
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.enabled
     *
     * @return the value of t_resource.enabled
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.enabled
     *
     * @param enabled the value for t_resource.enabled
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.remark
     *
     * @return the value of t_resource.remark
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.remark
     *
     * @param remark the value for t_resource.remark
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}