package com.example.blog.entity;

import java.util.Date;

public class Upvote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upvote.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upvote.user_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upvote.content_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String contentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upvote.ip
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upvote.upvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String upvote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upvote.downvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String downvote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_upvote.upvote_time
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private Date upvoteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upvote.id
     *
     * @return the value of t_upvote.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upvote.id
     *
     * @param id the value for t_upvote.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upvote.user_id
     *
     * @return the value of t_upvote.user_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upvote.user_id
     *
     * @param userId the value for t_upvote.user_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upvote.content_id
     *
     * @return the value of t_upvote.content_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upvote.content_id
     *
     * @param contentId the value for t_upvote.content_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setContentId(String contentId) {
        this.contentId = contentId == null ? null : contentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upvote.ip
     *
     * @return the value of t_upvote.ip
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upvote.ip
     *
     * @param ip the value for t_upvote.ip
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upvote.upvote
     *
     * @return the value of t_upvote.upvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getUpvote() {
        return upvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upvote.upvote
     *
     * @param upvote the value for t_upvote.upvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setUpvote(String upvote) {
        this.upvote = upvote == null ? null : upvote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upvote.downvote
     *
     * @return the value of t_upvote.downvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getDownvote() {
        return downvote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upvote.downvote
     *
     * @param downvote the value for t_upvote.downvote
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setDownvote(String downvote) {
        this.downvote = downvote == null ? null : downvote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_upvote.upvote_time
     *
     * @return the value of t_upvote.upvote_time
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public Date getUpvoteTime() {
        return upvoteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_upvote.upvote_time
     *
     * @param upvoteTime the value for t_upvote.upvote_time
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setUpvoteTime(Date upvoteTime) {
        this.upvoteTime = upvoteTime;
    }
}