package com.example.blog.entity;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.user_name
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.sex
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.birthday
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.hobby
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_info.address
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.id
     *
     * @return the value of t_user_info.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.id
     *
     * @param id the value for t_user_info.id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_id
     *
     * @return the value of t_user_info.user_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_id
     *
     * @param userId the value for t_user_info.user_id
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.user_name
     *
     * @return the value of t_user_info.user_name
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.user_name
     *
     * @param userName the value for t_user_info.user_name
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.sex
     *
     * @return the value of t_user_info.sex
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.sex
     *
     * @param sex the value for t_user_info.sex
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.birthday
     *
     * @return the value of t_user_info.birthday
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.birthday
     *
     * @param birthday the value for t_user_info.birthday
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.hobby
     *
     * @return the value of t_user_info.hobby
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.hobby
     *
     * @param hobby the value for t_user_info.hobby
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.address
     *
     * @return the value of t_user_info.address
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.address
     *
     * @param address the value for t_user_info.address
     *
     * @mbg.generated Tue Jul 17 16:26:37 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}